### ISSUE TITLE
[ENHANCEMENT] Allow toggle to not pass additional configuration in spec.metadata.instance.userdata in Hardware if in Cluster spec.clusterConfig.configURL is defined

### ISSUE THREAD

**Issue by irishgordo** [harvester/seeder#24]
If in a cluster yaml crd of:

```yaml
apiVersion: metal.harvesterhci.io/v1alpha1
kind: Cluster
metadata:
  name: david-mike-test
  namespace: seeder
spec:
  clusterConfig:
    configURL: http://REDACTED/iso/config/temp-airgap-test-config-url-delete-me-later.yaml
    nameservers:
      - REDACTED
  imageURL: http://REDACTED/iso
  nodes:
  - addressPoolReference:
      name: fast-vlan-static-pool
      namespace: seeder
    inventoryReference:
      name: hp-REDACTED
      namespace: seeder
  version: v1.2.1
  vipConfig:
    addressPoolReference:
      name: fast-vlan-static-pool
      namespace: seeder
```
is defined.

The Hardware that gets created in Seeder has:
```yaml

spec:
  disks:
  - device: /dev/sda
  interfaces:
  - dhcp:
      arch: x86_64
      hostname: hp-REDACTED-seeder
      ip:
        address: REDACTED
        gateway: REDACTED
        netmask: 255.255.248.0
      lease_time: 86400
      mac: 5c:b9:01:89:c6:f5
      uefi: true
    netboot:
      allowPXE: false
      osie:
        baseURL: http://REDACTED/iso
  metadata:
    facility:
      facility_code: on_prem
    instance:
      operating_system:
        distro: harvester
        version: v1.2.1
      userdata: harvester.install.config_url=http://REDACTED/iso/config/temp-airgap-test-config-url-delete-me-later.yaml
        harvester.install.management_interface.interfaces="hwAddr:5c:b9:01:89:c6:f5"
        ip=dhcp harvester.install.management_interface.method=dhcp harvester.management_interface.bond_options.mode=balance-tlb
        harvester.install.management_interface.bond_options.miimon=100 console=ttyS1,115200  harvester.install.mode=create
        harvester.token=Sw5Jdb5uYgFlq5k6 harvester.os.password=WGNqmNUWhnFBjTIH harvester.os.dns_nameservers=REDACTED  harvester.install.vip=REDACTED
        harvester.install.vip_mode=static harvester.install.iso_url=http://REDACTED/iso/v1.2.1/harvester-v1.2.1-amd64.iso
        harvester.install.device=/dev/sda  harvester.scheme_version=1
```

Which has `harvester.install.config_url` but it additionally has many many more configuration parameters passed in.
Which seems to then disregard what the `temp-airgap-test-config-url-delete-me-later.yaml` has inside of it.
As the parameters after the config_url, would override those listed in the config_url...seemingly.

Perhaps as a feature allow something like:
```yaml

apiVersion: metal.harvesterhci.io/v1alpha1
kind: Cluster
metadata:
  name: david-mike-test
  namespace: seeder
spec:
  clusterConfig:
    configURL: http://REDACTED/iso/config/temp-airgap-test-config-url-delete-me-later.yaml
    configURLOverride: true
```
Where `spec.clusterConfig.configURLOverride` will build the

```go
	var metaDataStruct = `{{ if ne .ConfigURL ""}}harvester.install.config_url={{ .ConfigURL }}{{end}} harvester.install.networks.harvester-mgmt.interfaces="hwAddr:{{ .HWAddress }}" ip=dhcp harvester.install.networks.harvester-mgmt.method=dhcp harvester.install.networks.harvester-mgmt.bond_options.mode=balance-tlb harvester.install.networks.harvester-mgmt.bond_options.miimon=100 console=ttyS1,115200  harvester.install.mode={{ .Mode }} harvester.token={{ .Token }} harvester.os.password={{ .Password }} {{ range $v := .SSHKeys}}harvester.os.ssh_authorized_keys=\"- {{ $v }} \ "{{ end }}{{range $v := .Nameservers}}harvester.os.dns_nameservers={{ $v }} {{end}} harvester.install.vip={{ .VIP }} harvester.install.vip_mode=static harvester.install.iso_url={{ .IsoURL }} harvester.install.device={{ .Disk }} {{if eq .Mode "join"}}harvester.server_url={{ printf "https://%s:8443" .VIP }}{{end}}`
```

as something like (rough pseudo code):
```go
package main

func main() {

	if configURLOverride != nil {
		var metaDataStruct = `{{ if ne .ConfigURL ""}}harvester.install.config_url={{ .ConfigURL }}{{end}}`
	} else {
		var metaDataStruct = `{{ if ne .ConfigURL ""}}harvester.install.config_url={{ .ConfigURL }}{{end}} harvester.install.networks.harvester-mgmt.interfaces="hwAddr:{{ .HWAddress }}" ip=dhcp harvester.install.networks.harvester-mgmt.method=dhcp harvester.install.networks.harvester-mgmt.bond_options.mode=balance-tlb harvester.install.networks.harvester-mgmt.bond_options.miimon=100 console=ttyS1,115200  harvester.install.mode={{ .Mode }} harvester.token={{ .Token }} harvester.os.password={{ .Password }} {{ range $v := .SSHKeys}}harvester.os.ssh_authorized_keys=\"- {{ $v }} \ "{{ end }}{{range $v := .Nameservers}}harvester.os.dns_nameservers={{ $v }} {{end}} harvester.install.vip={{ .VIP }} harvester.install.vip_mode=static harvester.install.iso_url={{ .IsoURL }} harvester.install.device={{ .Disk }} {{if eq .Mode "join"}}harvester.server_url={{ printf "https://%s:8443" .VIP }}{{end}}`
	}

}
```

To prevent additional params from overriding wht the config-url is providing.
